@echo on
echo Installing virtualenv...
pip install virtualenv
echo Creating a virtualenv...
python -m venv env
echo Openning the virtualenv...
.\env\Scripts\activate
echo Installing dependencies...
python -c "import monai"
pip install -qU "monai[ignite, nibabel, torchvision, tqdm, fire]==1.1.0"
pip install -r requirements.txt